.\" Manpage for otseca.
.\" Contact trimstray@gmail.com.
.TH man 8 "29.05.2018" "1.0.0" "otseca man page"
.SH NAME
otseca \- search and dump system configuration.
.SH SYNOPSIS
otseca <option|long-option>
.SH DESCRIPTION
otseca is a open source tool to search and dump system configuration.
.SH OPTIONS
--help
        show this message
.SH SEE ALSO
https://github.com/trimstray/otseca
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
