#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _grep()
#
# Description:
#   It helps in checking if the file contains the given string.
#
# Usage:
#   _grep string filename
#
# Examples:
#   _grep actions /etc/audit/audit.rules
#

function _grep() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="_grep"
  local _STATE=0

  local _string="$1"
  local _file="$2"

  # shellcheck disable=SC2155
  local _xoutput=$(grep "$_string" "$_file" 2>/dev/null)

  if [[ -e "$_file" ]] ; then

    if [[ ! -z "$_xoutput" ]] ; then

      printf "%s\\n" "$_xoutput"

      _STATE="1"

    else

      printf "string not found\\n"

      _STATE="0"

    fi

  else

    printf "file not found\\n"

    _STATE="254"

  fi

  return $_STATE

}
