#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _sysctl()
#
# Description:
#   It helps in checking whether the kernel param is enabled.
#
# Usage:
#   _sysctl service_name
#
# Examples:
#   _sysctl rsync
#

function _sysctl() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="_sysctl"
  local _STATE=0

  local _sname="$1"
  local _value="$2"

  # shellcheck disable=SC2155
  local _xoutput=$(sysctl "${_sname}" 2>/dev/null)

  if [[ ! "${_xoutput}" = *"= ${_value}"* ]] ; then

    printf "%s\\n" "$_xoutput"

    _STATE="0"

  else

    printf "%s\\n" "$_xoutput"

    _STATE="1"

  fi

  return $_STATE

}
