#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: _systemctl()
#
# Description:
#   It helps in checking whether the service is enabled.
#
# Usage:
#   _systemctl service_name
#
# Examples:
#   _systemctl rsync
#

function _systemctl() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="_systemctl"
  local _STATE=0

  local _service_name="$1"

  # shellcheck disable=SC2155
  local _xoutput=$(systemctl list-unit-files --state=enabled "${_service_name}.service" 2>/dev/null)

  if [[ ! "${_xoutput}" = *"${_service_name}"* ]] ; then

    printf "%s\\n" "$_xoutput"

    _STATE="0"

  else

    printf "%s\\n" "$_xoutput"

    _STATE="1"

  fi

  return $_STATE

}
