#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DumpSysInfo()
#
# Description:
#   Dump system information.
#
# Usage:
#   DumpSysInfo
#
# Examples:
#   DumpSysInfo
#

function DumpSysInfo() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DumpSysInfo"
  local _STATE=0

  _msg_args+=(\
  "checking conn: ${_addr}:${_port}")

  _cmd_args+=(\
  "eval timeout 1 bash -c \"</dev/tcp/${_addr}/${_port}\"")

  _STATE="$?"

  return $_STATE

}
