#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DumpSysInfo()
#
# Description:
#   Dump system information.
#
# Usage:
#   DumpSysInfo
#
# Examples:
#   DumpSysInfo
#

function DumpSysInfo() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DumpSysInfo"
  local _STATE=0

  local _arg=("${@:1}")

  _msg_args+=(\
  "\"${_arg[@]}\"")

  _cmd_args+=(\
  "${_arg[@]}")

  _STATE="$?"

  return $_STATE

}
