#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: GenReport()
#
# Description:
#   Generate report.
#
# Usage:
#   GenReport
#
# Examples:
#   GenReport
#

function GenReport() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="GenReport"
  local _STATE=0

  # shellcheck disable=SC2034
  _fd_postfix="$1"

  # shellcheck disable=SC2034,SC2154
  _output_data="${_report}/${_fd_postfix}"

  # shellcheck disable=SC2154
  printf "%s\\n" \
"
<div class=\"limiter\">
<div class=\"container-table100\">
<div class=\"wrap-table100\">
<div class=\"table100 ver1 m-b-110\">

<div class=\"table100-head\">
<table>
<thead>
<tr class=\"row100 head\">
<th class=\"cell100 column1\" style=\"background-color: ${_color};\">COMMAND: ${_command}</th>
</tr>
</thead>
</table>
</div>
<div class=\"table100-body js-pscroll\">
<table>
<tbody>
<tr class=\"row100 body\">
<td class=\"cell100 column1\">
<pre><code>${_output}</pre></code>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
" \
  >> "${_output_data}"

  _output_data="${_report}"

  _STATE="$?"

  return $_STATE

}
