#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: InitTasks()
#
# Description:
#   Initialize tasks.
#
# Usage:
#   InitTasks
#
# Examples:
#   InitTasks
#

function InitTasks() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="InitTasks"
  local _STATE=0

  local _task_type="$1"

  local _msg_pass
  local _msg_fail

  if [[ "${#_STACK[@]}" -ne 0 ]] ; then

    printf "     \\e[0;1;36m%s\\e[m task: \\e[1;1;33m%s\\e[m\\n" \
          "×" "$(echo "$_task_type" | tr '[:lower:]' '[:upper:]')"

    printf "     %s\\n" \
          "¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨"

    # shellcheck disable=SC2034
    _tcount=0

    OIFS="$IFS"
    IFS=$'\n'

    for _i in "${_STACK[@]}" ; do

      # shellcheck disable=SC2034
      _th_local_color_fail="false"

      # shellcheck disable=SC2034,SC2154
      _dump_log="${_dump_dir}/dump.log.${_tdate}-${_task_type}-${_tcount}"

      _trim_cmd=$(echo "${_i}" | cut -c -54)

      if [[ "$_i" = *"_exec"* ]] ; then

        # shellcheck disable=SC2034
        _msg_pass="INIT"
        # shellcheck disable=SC2034
        _msg_fail="FAIL"

        # shellcheck disable=SC2034
        _th_local_color_fail="#606F7B"

        _xst=$(echo "${_i}" | cut -d " " -f2-)

        printf "    \\e[1;0;36m%s\\e[m \\e[2;2;37m%s\\e[m \\e[1;1;38m%s\\e[m" \
               " " "•" "${_xst}"

      elif [[ "$_i" = *"_sysctl"* ]] ; then

        # shellcheck disable=SC2034
        _msg_pass="DONE"
        # shellcheck disable=SC2034
        _msg_fail="FAIL"

        _xfd=$(echo "${_i}" | cut -d " " -f2)
        _xva=$(echo "${_i}" | cut -d " " -f3)

        printf "    \\e[1;0;36m%s\\e[m \\e[2;2;37m%s\\e[m \\e[1;1;38m%s = %d\\e[m" \
               " " "•" "${_xfd}" "${_xva}"

      elif [[ "$_i" = *"_grep"* ]] ; then

        # shellcheck disable=SC2034
        _msg_pass="FOUND"
        # shellcheck disable=SC2034
        _msg_fail="NOT FOUND"

        _xst=$(echo "${_i}" | cut -d " " -f2)
        _xfd=$(echo "${_i}" | cut -d " " -f3)

        printf "    \\e[1;0;36m%s\\e[m \\e[2;2;37m%s\\e[m \\e[1;1;38m%s in %s\\e[m" \
               " " "•" "${_xst}" "${_xfd}"

      else

        # shellcheck disable=SC2034
        _msg_pass="DONE"
        # shellcheck disable=SC2034
        _msg_fail="FAIL"

        printf "    \\e[1;0;36m%s\\e[m \\e[2;2;37m%s\\e[m \\e[1;1;38m%s\\e[m" \
               " " "•" "${_trim_cmd}"

      fi

      _init_cmd "${_i}"

      _tcount=$((_tcount + 1))

    done

    IFS="$OIFS"

    unset _i

    echo

  fi

  _STATE="$?"

  return $_STATE

}
