#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: InitTasks()
#
# Description:
#   Initialize tasks.
#
# Usage:
#   InitTasks
#
# Examples:
#   InitTasks
#

function InitTasks() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="InitTasks"
  local _STATE=0

  local _task_type="$1"

  printf "     \\e[0;1;36m%s\\e[m task: \\e[1;1;33m%s\\e[m\\n" \
         "×" "$(echo "$_task_type" | tr '[:lower:]' '[:upper:]')"

  printf "     %s\\n" \
         "¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨"

  # shellcheck disable=SC2034
  _tcount=0

  OIFS="$IFS"
  IFS=$'\n'

  for _i in "${_STACK[@]}" ; do

    # shellcheck disable=SC2034,SC2154
    _dump_log="${_dump_dir}/dump.log.${_tdate}-${_task_type}-${_tcount}"

   _trim_cmd=$(echo "${_i}" | cut -c -54)

    printf "    \\e[1;0;36m%s\\e[m \\e[2;2;37m%s\\e[m \\e[1;1;38m%s\\e[m" \
           " " "•" "${_trim_cmd}"

    _init_cmd "${_i}"

    _tcount=$((_tcount + 1))

  done

  IFS="$OIFS"

  unset _i

  echo

  _STATE="$?"

  return $_STATE

}
