#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: SearchSysInfo()
#
# Description:
#   Search system information.
#
# Usage:
#   SearchSysInfo
#
# Examples:
#   SearchSysInfo
#

function SearchSysInfo() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="SearchSysInfo"
  local _STATE=0

  _STATE="$?"

  return $_STATE

}
