#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: SetReportType()
#
# Description:
#   Set env for generate report.
#
# Usage:
#   SetReportType
#
# Examples:
#   SetReportType
#

function SetReportType() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="SetReportType"
  local _STATE=0

  local _dlog="$1"

  # shellcheck disable=SC2034
  _tcount=0

  for _res in "${_TASKS[@]}" ; do

    # shellcheck disable=SC2034,SC2154
    _dump_log="${_dlog}-${_tcount}"

    printf "   \\e[1;0;36m%s\\e[m \\e[2;2;37m%s\\e[m \\e[1;1;38m%s\\e[m" \
           " " "•" "${_res}"

    _init_function "DumpSysInfo \"${_res}\""

    _tcount=$((_tcount + 1))

  done

  _STATE="$?"

  return $_STATE

}
